# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#' @export
compute_simpson_index <- function(D, knn_idx, batch_labels, n_batches, perplexity = 15, tol = 1e-5) {
    .Call('_lisi_compute_simpson_index', PACKAGE = 'lisi', D, knn_idx, batch_labels, n_batches, perplexity, tol)
}

