fail_fast: false
default_language_version:
    python: python3
default_stages:
-   commit
-   push
minimum_pre_commit_version: 2.16.0
repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8
        args: [-i]
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
    -   id: yesqa
        additional_dependencies:
        -   flake8-tidy-imports
        -   flake8-docstrings
        -   flake8-rst-docstrings
        -   flake8-comprehensions
        -   flake8-bugbear
        -   flake8-blind-except
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: detect-private-key
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace
        exclude: setup.cfg
    -   id: check-case-conflict
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args:
        -   --in-place
        -   --remove-all-unused-imports
        -   --remove-unused-variable
        -   --ignore-init-module-imports
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-tidy-imports
        -   flake8-docstrings
        -   flake8-rst-docstrings
        -   flake8-comprehensions
        -   flake8-bugbear
        -   flake8-blind-except
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
    -   id: pyupgrade
        args: [--py3-plus, --py37-plus, --keep-runtime-typing]
