name: Build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.7', '3.9']
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build
      run: python3 -m pip install --upgrade build twine

    - name: Build package
      run: |
        python -m build
        twine check dist/*

    - name: Install package
      run: |
        pip install dist/*.whl
        cd tests
        python -c 'import scib; print(scib.__version__)'
