name: Pre-commit

on: [push]

jobs:
  pre-commit:

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -e {0}

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.9']
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: python -m pip install --upgrade pip pre-commit

    - name: Run pre-commit
      run: |
        cd "$PROJECT_ROOT"
        git add .
        pre-commit run --color=always --show-diff-on-failure --all-files
